language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tonsuchat/docker-react -f Dockerfile.dev .

script:
  - docker run tonsuchat/docker-react npm run test -- --coverage
